# Generated by Django 3.1.5 on 2021-01-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisely', '0002_auto_20210114_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='morning_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=70)),
                ('value', models.CharField(max_length=10000)),
                ('date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisely.container')),
            ],
        ),
        migrations.CreateModel(
            name='evening_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=70)),
                ('value', models.CharField(max_length=100000)),
                ('date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisely.container')),
            ],
        ),
    ]
