# Generated by Django 3.1.5 on 2021-01-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisely', '0005_auto_20210114_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evening_entry',
            old_name='date_id',
            new_name='date',
        ),
    ]
